#!/usr/bin/env python3
"""Build the crons review page (crons/index.html) from cron definition mirrors.

Input: {repo_path: text} for every definition file, as collected by
sync_crons_to_git.py (the scheduler's read-only definition copies: the
shared cron.d directory and the per-goal crons directories). Output: bytes of a self-contained HTML page
listing every cron: title, schedule, owner, enabled state, delivery, and the
full job instructions in a collapsible block.

The page is regenerated by sync_crons_to_git.py on every sync, so it is
always current with the scheduler. It is served by GitHub Pages from the
cross-thread-task-status-tracker repo.
"""
import re
from datetime import datetime
from zoneinfo import ZoneInfo
from html import escape

TZ = ZoneInfo("America/Toronto")

# Friendly labels for chat ids seen in delivery lists.
CHAT_LABELS = {
    "b95fb15f-a58f-4547-b9cd-cdce882a5cd9": "For review thread",
    "1ea4c688-3d31-4f06-a369-180fd5e00405": "Main chat",
}


def parse_frontmatter(text):
    """Minimal frontmatter parser: top-level keys + one nested schedule block."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}, ""
    fm, body = m.group(1), text[m.end():]
    data, cur_key = {}, None
    for line in fm.splitlines():
        if re.match(r"^\S", line):
            k, _, v = line.partition(":")
            cur_key = k.strip()
            data[cur_key] = v.strip().strip("'\"")
        elif line.startswith("  ") and cur_key:
            k, _, v = line.strip().partition(":")
            if not isinstance(data.get(cur_key), dict):
                data[cur_key] = {}
            data[cur_key][k.strip()] = v.strip().strip("'\"")
    return data, body.strip()


def human_schedule(fm):
    s = fm.get("schedule", {}) if isinstance(fm.get("schedule"), dict) else {}
    kind = s.get("kind", "?")
    t = s.get("time", "")
    hhmm = t[:5] if len(t) >= 5 else t
    if kind == "daily":
        return f"Daily {hhmm}".strip()
    if kind == "interval":
        return f"Every {s.get('every', '?')}"
    if kind == "weekly":
        return f"Weekly {', '.join([d for d in [s.get('dow', '')] if d])} {hhmm}".strip()
    if kind == "monthly":
        return f"Monthly (day {s.get('dom', '?')}) {hhmm}".strip()
    if kind == "runonce":
        return f"Once {s.get('at', '?')}"
    return kind


def owner_label(fm, repo_path):
    owner = fm.get("owner", "")
    if owner.startswith("goal:"):
        return owner[5:]
    if "/goals/" in repo_path:
        m = re.search(r"/goals/([^/]+)/", repo_path)
        if m:
            return m.group(1)
    if "system-cron" in repo_path or "system_cron" in repo_path:
        return "system"
    return "shared"


def delivery_label(fm):
    raw = fm.get("delivery", "")
    if isinstance(raw, dict):
        raw = " ".join(str(v) for v in raw.values())
    ids = re.findall(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", raw)
    if not ids:
        return "—"
    return ", ".join(CHAT_LABELS.get(i, i[:8] + "…") for i in ids)


def build_page(defs):
    """defs: {repo_path: text}. Returns HTML bytes."""
    crons = []
    for path, text in sorted(defs.items()):
        if not path.endswith(".md") or path.endswith("README.md"):
            continue
        fm, body = parse_frontmatter(text)
        if not fm.get("id"):
            continue
        crons.append({
            "id": fm.get("id", "?"),
            "title": fm.get("title", fm.get("id", "?")),
            "enabled": fm.get("enabled", "true") == "true",
            "schedule": human_schedule(fm),
            "tz": (fm.get("schedule", {}) or {}).get("timezone", ""),
            "owner": owner_label(fm, path),
            "delivery": delivery_label(fm),
            "body": body,
        })

    groups = {}
    for c in crons:
        groups.setdefault(c["owner"], []).append(c)
    for g in groups.values():
        g.sort(key=lambda c: (c["schedule"], c["id"]))

    now = datetime.now(TZ).strftime("%Y-%m-%d %H:%M %Z")
    total = len(crons)
    enabled_n = sum(1 for c in crons if c["enabled"])

    parts = ["""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Scheduled jobs — all crons</title>
<style>
body{font-family:system-ui,-apple-system,sans-serif;max-width:1100px;margin:0 auto;
padding:16px;color:#1a1a1a;background:#fff}
h1{font-size:1.4em;margin:0 0 4px}h2{font-size:1.1em;margin:28px 0 8px;
border-bottom:2px solid #eee;padding-bottom:4px}
.meta{color:#666;font-size:.85em;margin-bottom:16px}
table{width:100%;border-collapse:collapse;font-size:.88em}
th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #eee;vertical-align:top}
th{background:#f7f7f7}tr.disabled td{opacity:.45}
.badge{display:inline-block;padding:1px 8px;border-radius:10px;font-size:.78em}
.on{background:#e6f4ea;color:#1a7f37}.off{background:#fce8e6;color:#b3261e}
details{margin-top:6px}summary{cursor:pointer;color:#1a73e8;font-size:.85em}
pre{white-space:pre-wrap;background:#f7f7f7;padding:10px;border-radius:6px;
font-size:.82em;max-height:300px;overflow:auto}
.id{font-family:monospace;font-size:.82em;color:#555}
@media(prefers-color-scheme:dark){body{background:#121212;color:#e0e0e0}
th{background:#1e1e1e}td,th{border-color:#333}pre{background:#1e1e1e}
.meta{color:#999}.id{color:#aaa}}
</style></head><body>
<h1>Scheduled jobs</h1>
<div class="meta">Every saved cron, regenerated from the scheduler on each sync.
Generated: """ + escape(now) + f" &middot; {total} jobs, {enabled_n} enabled.</div>"]

    for owner in sorted(groups):
        g = groups[owner]
        parts.append(f"<h2>{escape(owner)} ({len(g)})</h2>")
        parts.append("<table><tr><th>Job</th><th>Schedule</th><th>Status</th>"
                     "<th>Delivers to</th></tr>")
        for c in g:
            cls = "" if c["enabled"] else ' class="disabled"'
            badge = ('<span class="badge on">enabled</span>' if c["enabled"]
                     else '<span class="badge off">disabled</span>')
            tz = f'<div class="id">{escape(c["tz"])}</div>' if c["tz"] else ""
            parts.append(
                f"<tr{cls}><td><b>{escape(c['title'])}</b>"
                f'<div class="id">{escape(c["id"])}</div>'
                f"<details><summary>job instructions</summary>"
                f"<pre>{escape(c['body'])}</pre></details></td>"
                f"<td>{escape(c['schedule'])}{tz}</td>"
                f"<td>{badge}</td><td>{escape(c['delivery'])}</td></tr>")
        parts.append("</table>")

    parts.append(f'<div class="meta" style="margin-top:32px">Page generated {escape(now)} '
                 "from the scheduler's saved definitions. The scheduler is the source "
                 "of truth.</div></body></html>")
    return "\n".join(parts).encode()
